### ISSUE TITLE
EuterpiaTest misbehaves on Play

### ISSUE THREAD

**Issue by jxxcarlson** [jxxcarlson/DrumLanguage#1]
Load `EuterpiaTest` by clicking on `./app/euterpia-test.elm`.  Press play.  The displayed melody is played (twice).  Now press Play again, even after a suitable pause.  No response.  Now press Stop, then Play. It works, but this is not the work flow one desires.

**Comment by Orasund** [comment]
I believe the fix depends on what you want to accomplish. Tone.Transport is like a music sheet. Stopping and starting it again will just play the same sheet over and over again. The fix I propose chances stop to a pause, resulting in adding new content to the music sheet and then resuming where we left of. But this means that the current notes will first finish playing before the new tune starts.

Maybe a better solution is to stop the transport before we start it. But then what's the point of a transport anyway?

**Comment by Orasund** [comment]
After digging a bit in the API, I found `Transport.cancel()`. It cancels all the notes playing (but the Transport continues without any notes). This seams to be it. Still not sure why we use Transport though.
