### ISSUE TITLE
Play back issue.

### ISSUE THREAD

**Issue by jxxcarlson** [jxxcarlson/DrumLanguage#2]
Playback is not always correct.  In Example 1 below, it works as expected.  In Example 2 it does not.  Probably an issue with the way I have (ignorantly) configured `Tone.js`

## Example 1

The music"
```
c 3 qn, e 3 qn, g 3 qn, d 4 hn, c 4 wn
```

The data sent to `Tone.js`:
```
[{"time":"0","note":"C3","dur":"0.1875"},{"time":"0.1875","note":"E3","dur":"0.1875"},{"time":"0.375","note":"G3","dur":"0.1875"},{"time":"0.5625","note":"D4","dur":"0.375"},{"time":"0.9375","note":"C4","dur":"0.75"}]
```

## Example 2

The music:
```
c 3 qn, e 3 qn, g 3 qn, c 3 qn, e 3 qn, g 3 qn
```

The data sent to `Note.js`:
```
[{"time":"0","note":"C3","dur":"0.1875"},{"time":"0.1875","note":"E3","dur":"0.1875"},{"time":"0.375","note":"G3","dur":"0.1875"},{"time":"0.5625","note":"C3","dur":"0.1875"},{"time":"0.75","note":"E3","dur":"0.1875"},{"time":"0.9375","note":"G3","dur":"0.1875"}]
```

**Comment by Orasund** [comment]
I can't reproduce the data that you get for example 2.

I always get example 1, no matter what. I can reduce it back to the elm code: You always return `model.music` but never update it. You instead update model,voice1Music or voice2Music respectively.

I hope this fixes the problem.

**Comment by jxxcarlson** [comment]
Yes, that is fixed now
